language: node_js
cache:
    npm: false
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: YcRSWYkwc69CxiZ00bQzEbkj2KzYvxxVRovL0tlYiKiK2bffoy25W69wsvGTFhyo3EsBe6RNuKuV9Aq4G3W2G9dAJ3xjB5KDJ/qHdmu/BFqricyo2uKPjO9ug99HwCW9D2eYS9gr5k+Bqq5GJqc17bIoopSK7T9f0AmIWHMgIP0y/8KZnlO0uu+Cg8mmGz9YNQAN4+UYspYyNSQP69/cokp/IvGgLHTo5ulqBHh0DTH5jSzlwlLterFjWAl43meSwHVp8HpBs1D+1Zq8fx2v5C/aGJ/HnN7kcA9Ma/Ct/AnT17vMZOr3G3vc2ypts8VRuKu65XqLTRQXXIy7uM62xNx3e7f8bCr5vavrZKPPuxDO0/EISu7Bmy1EudoizfTxMH9n/Lid8FmxQ48FkD5QKVT/jkXBk55b99L7KWnmRSQK1bRm0ip17bbSPxzUj6roXiWwITCDniSssnMONZjbBEQAPHRw7NsEEPMX8wxRkV4Brda4ce+xz9Knf700RCfB0HhCucFv/2erWrMSLUF+v/Qdznud8r8eEVbsynz5iMiOuOWwh7iHwOZ5qSeOaHh9XDcpgcIq1GmJyzjB2VDkfkPsfJEnlnApgKxpCNIJ8xtvPHkiABwqgsUrsnb5a/ZyxswZSr2+MwCjWXsNT0venzEPze5gp8eFHbamvnueeEc=
