language: node_js
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: orlTlVoL2gzKnOu7bNMQzlFwQECQT9mImXitnRF1oTylcsYxz1hKiTMIMb2ghOJkLnDxcweYaz2D2kGZmN0a/ysdK7FGZla1PvatShcKka0XOcslzCmheyywIy+fBbV3r4TmFdX0ipNfE8w8nhX30d2iJ8m9PZONDMOA3OgcMkkYF8rEti1TU/ayZyxi9xG3Ah1qv2dk79HK2NCSbba5t6rGR7FQAMw4+h0nEJ46D+SRiJArPsurU1h6r7T6Tv2vvaEAP2njhYNGkwtXsLLRZKxqaxIJIz1WdhdhTOw1cwXa9+Uf2ZeUeVz7Xwmphi/Xs37k92Lq3BrJ2fdz794YhckbeuIpjkheZ0F6djkfNq6XCkxgkX9Vbvi4HFsNx1EjgJuouuYh5kRaxCRL7AelQmls6gfyuI0htlX0/9OcxwUpcs34niWlhD5pfTXxw93yHuAN52VIpEabf53nC2E0EM/opawbetDR30uJByFidZ7lEmGY/3X6FBsAJygpdWKnq7gz97GeGcTF7yHL5PJaPZdDCLGTeKvm/eknBaMXl3z8jZBR0nr64aA2dN1m7SmFYRNsYOMPWE4Nv5z5t1WY8eySEpoDpWhmYIfiVY2pBhwx/L5PGA0GbVFd5T4kEqVO7O/5X+DVzdKJ9GKyTR91YSlNJRmEpwl+7YrGbVOVSJY=
